[package]
name = "gui"
version = "0.1.0"
authors = ["Dylan Gallagher <gallagdy@tcd.ie>"]
license = "MIT"
edition = "2021"

[dependencies]
article-extractor = { path = "../article-extractor" }
egui_graphs = { git = "https://github.com/blitzarx1/egui_graphs.git", branch = "master" }
egui = "0.27.0"
eframe = "0.27.0"
petgraph = "0.6"
